/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f103x6.h>
#include "Stm32_F103C6_GPIO.h"
#include "Stm32_F103C6_USART.h"
#include "lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


unsigned int IRQ_Flag = 0 ;
char *ch = "ahmed";


void UART_IRQ_Callback (void)
{
	MCAL_USART_Transmit_String(USART1, &ch, enable);
}

void clock_init()
{
	//Enable port A clock
	RCC_GPIOA_CLK_EN();
	//Enable port B clock
	RCC_GPIOB_CLK_EN();
	//Enable AFIO clock
	RCC_AFIO_CLK_EN();
}
void wait_ms(uint32_t time){
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}


int main(void)
{
	clock_init();
	lcd_init();
	lcd_clear();
	USART_CONFIG_t uartCFG;
	uartCFG.Baud_Rate = USART_BaudRate_9600;
	uartCFG.HW_FLW_CTRL = USART_HW_FLW_NONE;
	uartCFG.IRQ_Enable = USART_IRQ_RXNE;
	uartCFG.IRQ_HANDLER = UART_IRQ_Callback;
	uartCFG.Parity = USART_Parity_NONE;
	uartCFG.Word_Length = USART_WordLength_8BIT;
	uartCFG.Stop_Bits = USART_StopBits_1B;
	uartCFG.USART_Mode = USART_Mode_Transmitter_Receiver;
	MCAL_USART_Init(USART1, &uartCFG);
	MCAL_UART_GPIO_Set_Pins(USART1);
	while(1){

	}
}
