/*
 * se7en_segment.c
 *
 *  Created on: Apr 24, 2023
 *      Author: Ahmed Adel Wafdy
 */

#include "se7en_segment.h"
#include "Stm32_F103C6_GPIO.h"


GPIO_PIN_CONFIG_T PinCFG;
void se7ment_init(void){
	PinCFG.GPIO_PIN_NUMBER = GPIO_PIN_9;
	PinCFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &PinCFG);

	PinCFG.GPIO_PIN_NUMBER = GPIO_PIN_10;
	PinCFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &PinCFG);

	PinCFG.GPIO_PIN_NUMBER = GPIO_PIN_11;
	PinCFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &PinCFG);

	PinCFG.GPIO_PIN_NUMBER = GPIO_PIN_12;
	PinCFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &PinCFG);

	PinCFG.GPIO_PIN_NUMBER = GPIO_PIN_13;
	PinCFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &PinCFG);

	PinCFG.GPIO_PIN_NUMBER = GPIO_PIN_14;
	PinCFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &PinCFG);

	PinCFG.GPIO_PIN_NUMBER = GPIO_PIN_15;
	PinCFG.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &PinCFG);
}
